// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cksdthayfesprdrokffr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrc2R0aGF5ZmVzcHJkcm9rZmZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NTI5NDYsImV4cCI6MjA3MzMyODk0Nn0.NGBo3kVPtT3XiB--ImOvkIdvTJXgTtjDkhzBTjjvW7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});